name: Update Job
on:
  push:
    branches:
      - master

jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install and Build
        run: |
          npm install

      - name: update data
        run: |
          npm run update

      - name: generate csv
        run: |
          npm run csv

      - name: show files
        run: |
          ls -alh
          ls data -alh
          ls report -alh

      - name: Commit report
        run: |
          git config --global user.name 'Stefan Hofer'
          git config --global user.email 'stefan.hofer@me.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}