name: Update Job
on:
  schedule:
    - cron: '10 9-17 * * *'

jobs:
  update:
    name: Update data
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install and Build
        run: |
          npm install

      - name: update data
        run: |
          npm run update

      - name: generate csv
        run: |
          npm run csv

      - name: generate json
        run: |
          npm run json

      - name: show files
        run: |
          ls -alh
          ls data -alh
          ls docs/report -alh

      - name: Commit report
        run: |
          git config --global user.name 'Github Action Update Job'
          git config --global user.email 'info@122.co.at'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add data/*
          git commit -am "Date update commit"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}